version: '3.7'

services:
  kafka_server:
    image: bitnami/kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - mqttnet

  kafka-mqtt:
    image: confluentinc/cp-kafka-mqtt:latest
    network_mode: host
    depends_on:
      - mqttnet

  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mqttnet
 
  kafka-python-productor:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    networks:
      - mqttnet

  superset:
    image: acpmialj/ipmd:ssuperset
    ports:
      - "8080:8088"
    networks:
      - mqttnet

  druid:
    image: jdvelasq/druid:0.22.1
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "./:/workspace"
    networks:
      - mqttnet

networks:
  mqttnet:
    driver: bridge
